#Default port
server:
  port: 21314
#Profile switch
spring:
  thymeleaf:
    cache: true
    mode: HTML
    suffix: .html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, ${user.dir}/public/, file:D:/Workbench/Java_Project/OCHelper/table/public/
#File name & path, path must end with "/"
path:
  csv-item-name: itempanel.csv
  csv-fluid-name: fluid.csv
  json-item-name: indexItem.json
  json-fluid-name: indexFluid.json
  icon-panel-path: res/item_table/
  csv-path: D:/Workbench/Java_Project/OCHelper/table/dumpCSV/
  json-path: D:/Workbench/Java_Project/OCHelper/table/
  lua-scripts-path: D:/Workbench/Java_Project/OCHelper/scripts/server-side/
  database-path: D:/Workbench/Java_Project/OCHelper/database/
#Scheduled scan time (in ms)
scheduled:
  init: 20000
  rate: 30000
#More settings
values:
  keep-size: 500
  clean-schedule: 1000
  insight-size: 240
  energy-data-keep-size: 3000